# @package hydra.sweeper
params: 
  trainer.args.learning_rate: "tag(log, interval(0.1, 1.0))"
  trainer.method_args.cfg.act_quantile: "interval(0.8, 1)"
  trainer.method_args.cfg.act_pcs_to_use: "tag(log, range(30, 1000))"
  trainer.method_args.cfg.grad_pcs_to_use: "tag(log, range(30, 1000))"
