# @package hydra.sweeper
params:
  trainer.args.learning_rate: "tag(log, interval(1e-5, 5e-5))"
  trainer.method_args.alpha: "tag(log, interval(1, 5))"
  trainer.method_args.beta: "tag(log, interval(0.05, 0.5))"
