# @package hydra.sweeper
params:
  trainer.args.learning_rate: "tag(log, interval(5e-6, 5e-5))"
  trainer.method_args.beta: "interval(3.5, 4.5)"
  trainer.method_args.delta: "choice(0, 1)"
  trainer.method_args.gamma: "interval(0.125, 0.25)"
