model_args:
  pretrained_model_name_or_path: "deepseek-ai/DeepSeek-V2-Lite"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
  trust_remote_code: true
tokenizer_args:
  pretrained_model_name_or_path: "deepseek-ai/DeepSeek-V2-Lite"
  # trust_remote_code: true
template_args:
  apply_chat_template: false