model_args:
  pretrained_model_name_or_path: "meta-llama/Llama-3.1-8B"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "meta-llama/Llama-3.1-8B"
template_args:
  apply_chat_template: False