model_args:
  pretrained_model_name_or_path: "facebook/MobileLLM-125M"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
  trust_remote_code: True
tokenizer_args:
  pretrained_model_name_or_path: "facebook/MobileLLM-125M"
  trust_remote_code: True
  use_fast: False
template_args:
  apply_chat_template: False