model_args:
  pretrained_model_name_or_path: "Qwen/Qwen1.5-MoE-A2.7B"
  # for Qwen2Noe, flash attention conflicts with right padding
  attn_implementation: null
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "Qwen/Qwen1.5-MoE-A2.7B"
template_args:
  apply_chat_template: false